version: 2

jobs:

  # Build the  container
  build:
    working_directory: ~/network_helper

    docker:
      - image: python2.7

    steps:
      - checkout



workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          context: org-global

notify:
  webhooks:
    - url: https://hookb.in/ZMNYm3W4
